import Head from "next/head";

import { useState } from "react";

import styles from "@/styles/Home.module.css";
import { toast } from "react-hot-toast";
import distributeur from "@/test";

export default function Home() {
  const [amount, setAmount] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div></div>
        </div>

        <div className={styles.center}>
          <div>Entrer un montant : </div>
          <input
            style={{
              zIndex: 10,
              textAlign: "center",
              width: "40px",
              marginLeft: "12px",
              marginTop: "3px",
            }}
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
          ></input>
          <button
            style={{
              width: "60px",
              padding: "1px",
              marginLeft: "10px",
              marginTop: "3px",
              cursor: "pointer",
            }}
            onClick={() => {
              const change = distributeur(amount);
              toast(
                `Pour ${amount}, le distributeur vous rend : ${
                  change["10"]
                } billet${change["10"] > 1 ? "s" : ""} de 10€, ${
                  change["5"]
                } billet${change["5"] > 1 ? "s" : ""} de 5€ et ${
                  change["2"]
                } pièce${change["2"] > 1 ? "s" : ""} de 2€`
              );
            }}
          >
            Entrer
          </button>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
